# config.yaml (final, correct version)
jobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
      replicaCount: 1
      containerSpec:
        imageUri: europe-west3-docker.pkg.dev/tinnitus-project-98765/tinnitus-repo/tinnitus-trainer:latest
        command:
          - python3
          - train.py